### ISSUE TITLE
good-first-bug keyword

### ISSUE THREAD

**Issue by jryans** [captainbrosset/devtools-bug-finder#22]
Bugzilla is moving towards using a good-first-bug _keyword_ instead of a whiteboard tag. See [bug 1279238](https://bugzilla.mozilla.org/show_bug.cgi?id=1279238). We should update the tool to handle this case.

**Comment by captainbrosset** [comment]
Thanks for filing. I guess we'll need to search for bugs that either have the whiteboard tag or the keyword or both.

**Comment by captainbrosset** [comment]
Fixed by 92ba3218c5392663bbc43ed03df78455c156fa3b
What I ended up doing is mass updating all the devtools bugs that had the good first bug whiteboard flag so that they now also have the keyword.
This way I don't have to do 2 requests (not sure I can search for bugs that have either the flag or the keyword with the API, and doing the update in bugzilla was easy enough).
